version: '2'
services:
    daners-app:
        image: daners
        external_links:
            - daners-postgresql:postgresql
            - daners-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/daners
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    daners-postgresql:
        extends:
            file: postgresql.yml
            service: daners-postgresql
    daners-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: daners-elasticsearch
